repos:
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 648203cec3e499b9eff54a24d6cf4b25ce02eb1e  # frozen: v1.14.0
  hooks:
  - id: mypy
    additional_dependencies:
    - types-docutils
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b  # frozen: v5.0.0
  hooks:
  - id: check-yaml
    exclude: '.\.gaphor'
  - id: trailing-whitespace
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: a23f6b85d0fdd5bb9d564e2579e678033debbdff  # frozen: v0.10.0.1
  hooks:
  - id: shellcheck
    args: [--exclude, SC1017]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'f0b5944bef86f50d875305821a0ab0d8c601e465'  # frozen: v0.8.4
  hooks:
  - id: ruff
    args: [--fix, --preview]
  - id: ruff-format
    types_or: [python, spec]
